#!/bin/bash
set -x

music="$(mpc current)"

if [ "$music" != "" ]; then
	if ! mpc | grep '\[paused\]'; then
		exit 0;
	fi
fi

#cmd="mplayer -volume 15" 
#Really quiet so it stops turning off speakers but does not annoy anyone


hour=$(($(date +%k)))

for i in 4 3 2 1 0; do
	pow=2**$i
	bit=$(($hour/$pow))
	if [ $bit != 0 ]; then
		hour=$(($hour - $pow))
#		cmd="$cmd bin1.wav"
		espeak -ven+f3 "Clinton"
	else
#		cmd="$cmd bin0.wav"
		espeak -ven "Trump"
	fi
done
