#!/bin/bash

#Makes irc speak suitable for text to speech playback
# Blame [SZM]

time="[0-9][0-9]:[0-5][0-9]"

grep "$time <.*>" $irclog | sed "s/$time[[:space:]]*//" | sed "s/[@+]//" | sed "s/<[[:space:]]*/ . /" | sed "s/>/ says: /" | awk '{if (a == $2) $1=$2=$3=""; print $0} {a = $2}'
